import dotenv from "dotenv";
import { connectDB } from "../config/db.js";
import Product from "../models/Product.js";

dotenv.config();

const baseProducts = [
  // 1. ELECTRONICS
  {
    name: "Aurora Noise-Cancel Headphones",
    category: "Electronics",
    brand: "Aurora Audio",
    price: 249,
    oldPrice: 319,
    rating: 4.8,
    numReviews: 412,
    countInStock: 34,
    isFeatured: true,
    tags: ["audio", "wireless", "headphones"],
    features: ["Active noise cancellation", "40-hour battery life", "Hi-res wireless audio"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Zenith Smartwatch Pro",
    category: "Electronics",
    brand: "Zenith",
    price: 299,
    oldPrice: 379,
    rating: 4.7,
    numReviews: 355,
    countInStock: 28,
    isFeatured: true,
    tags: ["wearable", "health", "smartwatch"],
    features: ["AMOLED always-on display", "Sleep and heart tracking", "5ATM water resistance"],
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Nebula 4K Action Camera",
    category: "Electronics",
    brand: "Nebula Optics",
    price: 219,
    oldPrice: 279,
    rating: 4.5,
    numReviews: 188,
    countInStock: 22,
    isFeatured: false,
    tags: ["camera", "travel", "4k"],
    features: ["4K60 recording", "Stabilized footage", "Waterproof housing"],
    image: "https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "AeroBook Carbon 14",
    category: "Electronics",
    brand: "AeroCompute",
    price: 1399,
    oldPrice: 1599,
    rating: 4.9,
    numReviews: 132,
    countInStock: 15,
    isFeatured: true,
    tags: ["laptop", "productivity", "ultrabook"],
    features: ["14-inch 2.8K display", "Carbon fiber chassis", "All-day battery"],
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Lumen Bluetooth Speaker",
    category: "Electronics",
    brand: "Lumen Sound",
    price: 159,
    oldPrice: 209,
    rating: 4.6,
    numReviews: 241,
    countInStock: 40,
    isFeatured: false,
    tags: ["speaker", "portable", "party"],
    features: ["360-degree sound", "IPX7 splash resistance", "Deep bass tuning"],
    image: "https://images.unsplash.com/photo-1589003077984-894e133dabab?auto=format&fit=crop&w=1200&q=80",
  },

  // 2. FASHION
  {
    name: "AeroFlex Tailored Blazer",
    category: "Fashion",
    brand: "Aero Style",
    price: 179,
    oldPrice: 229,
    rating: 4.6,
    numReviews: 205,
    countInStock: 26,
    isFeatured: true,
    tags: ["blazer", "minimal", "premium"],
    features: ["Wrinkle-resistant fabric", "Slim tailored silhouette", "Breathable inner lining"],
    image: "https://images.unsplash.com/photo-1593032465171-8bd2f2cf7d8d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Monarch Leather Sneakers",
    category: "Fashion",
    brand: "Monarch",
    price: 149,
    oldPrice: 189,
    rating: 4.4,
    numReviews: 168,
    countInStock: 33,
    isFeatured: false,
    tags: ["sneakers", "streetwear", "leather"],
    features: ["Full-grain leather upper", "Cushioned midsole", "Anti-slip rubber outsole"],
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Velvet Drape Evening Dress",
    category: "Fashion",
    brand: "Velveton",
    price: 199,
    oldPrice: 259,
    rating: 4.7,
    numReviews: 124,
    countInStock: 18,
    isFeatured: true,
    tags: ["dress", "evening", "luxury"],
    features: ["Soft velvet blend", "Elegant draped silhouette", "Concealed back zip"],
    image: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Urban Weave Backpack",
    category: "Fashion",
    brand: "Urban Weave",
    price: 119,
    oldPrice: 149,
    rating: 4.5,
    numReviews: 194,
    countInStock: 37,
    isFeatured: false,
    tags: ["backpack", "commute", "everyday"],
    features: ["Laptop sleeve", "Water-resistant shell", "Ergonomic shoulder straps"],
    image: "https://images.unsplash.com/photo-1509762774605-f07235a08f1f?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Noir Slim Chronograph",
    category: "Fashion",
    brand: "Noir Time",
    price: 229,
    oldPrice: 299,
    rating: 4.8,
    numReviews: 146,
    countInStock: 21,
    isFeatured: true,
    tags: ["watch", "chronograph", "accessory"],
    features: ["Sapphire-coated glass", "Japanese quartz movement", "Stainless steel case"],
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1200&q=80",
  },

  // 3. FITNESS
  {
    name: "Titan Adjustable Dumbbell Set",
    category: "Fitness",
    brand: "TitanFit",
    price: 349,
    oldPrice: 429,
    rating: 4.9,
    numReviews: 287,
    countInStock: 19,
    isFeatured: true,
    tags: ["gym", "weights", "home workout"],
    features: ["5-40kg quick adjust", "Space-saving design", "Knurled metal grip"],
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "PulseRun Carbon Shoes",
    category: "Fitness",
    brand: "PulseRun",
    price: 189,
    oldPrice: 239,
    rating: 4.6,
    numReviews: 213,
    countInStock: 31,
    isFeatured: false,
    tags: ["running", "shoes", "performance"],
    features: ["Carbon plate propulsion", "Breathable mesh upper", "Shock-absorbing foam"],
    image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "CoreBalance Yoga Mat Pro",
    category: "Fitness",
    brand: "CoreBalance",
    price: 89,
    oldPrice: 119,
    rating: 4.5,
    numReviews: 175,
    countInStock: 48,
    isFeatured: false,
    tags: ["yoga", "mat", "wellness"],
    features: ["Non-slip natural rubber", "6mm joint support", "Alignment guide texture"],
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "HydraSteel Smart Bottle",
    category: "Fitness",
    brand: "HydraSteel",
    price: 69,
    oldPrice: 99,
    rating: 4.3,
    numReviews: 132,
    countInStock: 62,
    isFeatured: false,
    tags: ["hydration", "smart", "lifestyle"],
    features: ["Hydration reminders", "Double-wall insulation", "App sync tracking"],
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "StrideMax Resistance Kit",
    category: "Fitness",
    brand: "StrideMax",
    price: 109,
    oldPrice: 149,
    rating: 4.4,
    numReviews: 121,
    countInStock: 29,
    isFeatured: false,
    tags: ["bands", "strength", "portable"],
    features: ["5 resistance levels", "Door anchor included", "Travel-friendly pouch"],
    image: "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?auto=format&fit=crop&w=1200&q=80",
  },

  // 4. GAMING
  {
    name: "Vortex X Gaming Console",
    category: "Gaming",
    brand: "Vortex",
    price: 599,
    oldPrice: 699,
    rating: 4.8,
    numReviews: 419,
    countInStock: 13,
    isFeatured: true,
    tags: ["console", "4k", "nextgen"],
    features: ["4K ultra-fast rendering", "Ray-traced graphics", "1TB SSD storage"],
    image: "https://images.unsplash.com/photo-1486401899868-0e435ed85128?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Phantom RGB Mechanical Keyboard",
    category: "Gaming",
    brand: "Phantom Gear",
    price: 159,
    oldPrice: 209,
    rating: 4.7,
    numReviews: 256,
    countInStock: 24,
    isFeatured: false,
    tags: ["keyboard", "rgb", "mechanical"],
    features: ["Hot-swappable switches", "Per-key RGB lighting", "Low-latency response"],
    image: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Apex Pro Gaming Mouse",
    category: "Gaming",
    brand: "Apex",
    price: 99,
    oldPrice: 139,
    rating: 4.6,
    numReviews: 302,
    countInStock: 45,
    isFeatured: false,
    tags: ["mouse", "esports", "wireless"],
    features: ["26K DPI optical sensor", "Ultra-light shell", "70-hour battery"],
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Immersion 34 Curved Monitor",
    category: "Gaming",
    brand: "Immersion",
    price: 729,
    oldPrice: 889,
    rating: 4.8,
    numReviews: 144,
    countInStock: 12,
    isFeatured: true,
    tags: ["monitor", "ultrawide", "144hz"],
    features: ["34-inch ultrawide QHD", "165Hz refresh rate", "1ms response time"],
    image: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "EchoPulse Gaming Headset",
    category: "Gaming",
    brand: "EchoPulse",
    price: 139,
    oldPrice: 179,
    rating: 4.5,
    numReviews: 212,
    countInStock: 38,
    isFeatured: false,
    tags: ["headset", "surround", "mic"],
    features: ["7.1 surround audio", "Detachable noise-cancel mic", "Memory foam earcups"],
    image: "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=1200&q=80",
  },

  // 5. HOME & LIVING
  {
    name: "Luma Smart Ambient Lamp",
    category: "Home",
    brand: "Luma Home",
    price: 129,
    oldPrice: 169,
    rating: 4.6,
    numReviews: 173,
    countInStock: 27,
    isFeatured: false,
    tags: ["lighting", "smart home", "decor"],
    features: ["Voice assistant compatible", "16M color scenes", "Schedule automation"],
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "PureBrew Precision Kettle",
    category: "Home",
    brand: "PureBrew",
    price: 119,
    oldPrice: 149,
    rating: 4.5,
    numReviews: 149,
    countInStock: 41,
    isFeatured: false,
    tags: ["kitchen", "coffee", "electric"],
    features: ["Gooseneck precision pour", "Temperature presets", "Quick boil system"],
    image: "https://images.unsplash.com/photo-1571552879083-e93b6ea70d1d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "AirNest Aroma Diffuser",
    category: "Home",
    brand: "AirNest",
    price: 79,
    oldPrice: 109,
    rating: 4.4,
    numReviews: 117,
    countInStock: 52,
    isFeatured: false,
    tags: ["aroma", "wellness", "decor"],
    features: ["Ultrasonic misting", "Whisper-quiet operation", "Auto shut-off protection"],
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Nexa Robot Vacuum S2",
    category: "Home",
    brand: "Nexa",
    price: 449,
    oldPrice: 569,
    rating: 4.7,
    numReviews: 263,
    countInStock: 17,
    isFeatured: true,
    tags: ["vacuum", "smart", "cleaning"],
    features: ["LiDAR room mapping", "Auto-empty dock support", "App and voice controls"],
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Breeze Linen Bedding Set",
    category: "Home",
    brand: "Breeze",
    price: 169,
    oldPrice: 219,
    rating: 4.6,
    numReviews: 98,
    countInStock: 23,
    isFeatured: false,
    tags: ["bedding", "linen", "comfort"],
    features: ["Breathable stonewashed linen", "Hypoallergenic fabric", "Deep-pocket fitted sheet"],
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
  },

  // 6. ACCESSORIES
  {
    name: "Orbit USB-C Dock Pro",
    category: "Accessories",
    brand: "Orbit",
    price: 189,
    oldPrice: 249,
    rating: 4.7,
    numReviews: 207,
    countInStock: 35,
    isFeatured: false,
    tags: ["dock", "usb-c", "workspace"],
    features: ["Dual 4K display output", "100W passthrough charging", "SD and Ethernet ports"],
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Aether MagSafe Power Bank",
    category: "Accessories",
    brand: "Aether",
    price: 89,
    oldPrice: 119,
    rating: 4.5,
    numReviews: 189,
    countInStock: 58,
    isFeatured: false,
    tags: ["power bank", "magsafe", "travel"],
    features: ["10,000mAh capacity", "Magnetic snap charging", "USB-C fast output"],
    image: "https://images.unsplash.com/photo-1587033411391-5d9e51cce126?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Luxe Leather Laptop Sleeve",
    category: "Accessories",
    brand: "Luxe Carry",
    price: 109,
    oldPrice: 149,
    rating: 4.6,
    numReviews: 141,
    countInStock: 30,
    isFeatured: false,
    tags: ["laptop", "sleeve", "leather"],
    features: ["Premium vegan leather", "Soft anti-scratch interior", "Magnetic secure closure"],
    image: "https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Vertex Pro Webcam 4K",
    category: "Accessories",
    brand: "Vertex",
    price: 169,
    oldPrice: 219,
    rating: 4.4,
    numReviews: 133,
    countInStock: 42,
    isFeatured: false,
    tags: ["webcam", "remote work", "4k"],
    features: ["4K clarity sensor", "Auto-light correction", "Dual beamforming microphones"],
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "PulseCharge Braided Cable Kit",
    category: "Accessories",
    brand: "PulseCharge",
    price: 49,
    oldPrice: 69,
    rating: 4.3,
    numReviews: 264,
    countInStock: 76,
    isFeatured: false,
    tags: ["cable", "charging", "durable"],
    features: ["Reinforced braided nylon", "USB-C / Lightning kit", "Fast-charge certified"],
    image: "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=1200&q=80",
  },

  // 7. BEAUTY & SKINCARE (NEW CATEGORY)
  {
    name: "Radiance Vitamin C Serum",
    category: "Beauty & Skincare",
    brand: "Botanique Glow",
    price: 54,
    oldPrice: 75,
    rating: 4.9,
    numReviews: 320,
    countInStock: 45,
    isFeatured: true,
    tags: ["serum", "skincare", "glow"],
    features: ["Pure 20% Vitamin C", "Hyaluronic acid base", "Dermatologist approved"],
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Hydrating Rose Botanical Toner",
    category: "Beauty & Skincare",
    brand: "Botanique Glow",
    price: 38,
    oldPrice: 50,
    rating: 4.7,
    numReviews: 184,
    countInStock: 60,
    isFeatured: false,
    tags: ["toner", "organic", "rose"],
    features: ["Distilled Damask rose", "Alcohol-free formulation", "Pore tightening extract"],
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Golden Argan Hair Elixir",
    category: "Beauty & Skincare",
    brand: "LuxeLocks",
    price: 46,
    oldPrice: 62,
    rating: 4.8,
    numReviews: 210,
    countInStock: 38,
    isFeatured: false,
    tags: ["hair care", "argan oil", "repair"],
    features: ["Cold-pressed Moroccan Argan", "Heat protection up to 230C", "Non-greasy shine"],
    image: "https://images.unsplash.com/photo-1608248597359-2e6840742183?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Velvet Matte Luxe Lipstick Duo",
    category: "Beauty & Skincare",
    brand: "Maison Velvet",
    price: 42,
    oldPrice: 58,
    rating: 4.6,
    numReviews: 156,
    countInStock: 50,
    isFeatured: true,
    tags: ["lipstick", "makeup", "cosmetics"],
    features: ["16-hour longwear pigment", "Enriched with Vitamin E", "Feather-light velvet touch"],
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Sonic Facial Cleansing Brush",
    category: "Beauty & Skincare",
    brand: "GlowTech",
    price: 89,
    oldPrice: 120,
    rating: 4.7,
    numReviews: 195,
    countInStock: 25,
    isFeatured: false,
    tags: ["beauty tech", "cleanser", "waterproof"],
    features: ["Ultra-hygienic silicone bristles", "8000 T-Sonic pulsations/min", "USB rechargeable"],
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Midnight Recovery Peptide Night Cream",
    category: "Beauty & Skincare",
    brand: "LuxeBotanics",
    price: 68,
    oldPrice: 89,
    rating: 4.8,
    numReviews: 240,
    countInStock: 35,
    isFeatured: true,
    tags: ["anti-aging", "night cream", "peptide"],
    features: ["Tri-peptide collagen complex", "Deep overnight cellular hydration", "Hypoallergenic and fragrance-free"],
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Charcoal Detox Clarifying Clay Mask",
    category: "Beauty & Skincare",
    brand: "Botanique Glow",
    price: 34,
    oldPrice: 45,
    rating: 4.7,
    numReviews: 175,
    countInStock: 42,
    isFeatured: false,
    tags: ["clay mask", "detox", "pores"],
    features: ["Active activated bamboo charcoal", "Kaolin and Bentonite clay blend", "Soothes redness and controls oil"],
    image: "https://images.unsplash.com/photo-1556228722-d0b5d034abae?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Invisible UV Shield Mineral SPF 50",
    category: "Beauty & Skincare",
    brand: "Solaris Care",
    price: 39,
    oldPrice: 52,
    rating: 4.9,
    numReviews: 285,
    countInStock: 50,
    isFeatured: true,
    tags: ["sunscreen", "spf50", "mineral"],
    features: ["100% non-nano zinc oxide", "Zero white cast sheer finish", "Reef-friendly broad spectrum protection"],
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1200&q=80",
  },

  // 8. AUDIO & STUDIO (NEW CATEGORY)
  {
    name: "Studio Pro Condenser Microphone",
    category: "Audio & Studio",
    brand: "SoundForge",
    price: 199,
    oldPrice: 259,
    rating: 4.8,
    numReviews: 230,
    countInStock: 20,
    isFeatured: true,
    tags: ["microphone", "studio", "podcast"],
    features: ["Cardioid condenser capsule", "Zero-latency monitoring", "Integrated pop shield"],
    image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Vintage Hi-Fi Vinyl Turntable",
    category: "Audio & Studio",
    brand: "RetroAcoustics",
    price: 289,
    oldPrice: 360,
    rating: 4.9,
    numReviews: 178,
    countInStock: 16,
    isFeatured: true,
    tags: ["vinyl", "turntable", "audiophile"],
    features: ["Belt-driven 3-speed playback", "Built-in Bluetooth transmitter", "Solid walnut plinth"],
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Audiophile Desktop DAC & Amp",
    category: "Audio & Studio",
    brand: "SonicMaster",
    price: 169,
    oldPrice: 219,
    rating: 4.7,
    numReviews: 142,
    countInStock: 30,
    isFeatured: false,
    tags: ["dac", "amp", "hifi"],
    features: ["32-bit/384kHz decoding", "Balanced XLR output", "Aluminum CNC enclosure"],
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Heavy-Duty Studio Boom Arm",
    category: "Audio & Studio",
    brand: "SoundForge",
    price: 79,
    oldPrice: 109,
    rating: 4.6,
    numReviews: 165,
    countInStock: 44,
    isFeatured: false,
    tags: ["boom arm", "desk mount", "streaming"],
    features: ["Internal spring suspension", "Integrated cable management", "360-degree rotation"],
    image: "https://images.unsplash.com/photo-1583244532610-2a234e7c3eca?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Acoustic Shield Reflection Filter",
    category: "Audio & Studio",
    brand: "AcousticPro",
    price: 99,
    oldPrice: 135,
    rating: 4.5,
    numReviews: 118,
    countInStock: 22,
    isFeatured: false,
    tags: ["acoustic", "recording", "isolation"],
    features: ["High-density acoustic foam", "Foldable 5-panel design", "Universal mic mount"],
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Reference Pro Open-Back Studio Headphones",
    category: "Audio & Studio",
    brand: "SoundForge",
    price: 349,
    oldPrice: 429,
    rating: 4.9,
    numReviews: 198,
    countInStock: 18,
    isFeatured: true,
    tags: ["headphones", "studio monitor", "mixing"],
    features: ["50mm planar dynamic drivers", "Open-back wide soundstage design", "Velour memory foam ear pads"],
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Portable 32-bit Field Audio Recorder",
    category: "Audio & Studio",
    brand: "SonicMaster",
    price: 229,
    oldPrice: 289,
    rating: 4.8,
    numReviews: 154,
    countInStock: 24,
    isFeatured: false,
    tags: ["recorder", "field audio", "32-bit float"],
    features: ["32-bit float dual AD converters", "Built-in X/Y stereo microphones", "Timecode synchronization support"],
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Studio Monitor Acoustic Isolation Stands",
    category: "Audio & Studio",
    brand: "AcousticPro",
    price: 59,
    oldPrice: 79,
    rating: 4.6,
    numReviews: 130,
    countInStock: 40,
    isFeatured: false,
    tags: ["stands", "isolation", "speakers"],
    features: ["High-density damping foam", "Adjustable tilt angle up to 15 degrees", "Eliminates unwanted bass resonance"],
    image: "https://images.unsplash.com/photo-1558089687-f282ffcbc126?auto=format&fit=crop&w=1200&q=80",
  },

  // 9. KITCHEN & GOURMET (NEW CATEGORY)
  {
    name: "Barista Touch Espresso Machine",
    category: "Kitchen & Gourmet",
    brand: "Crema & Bean",
    price: 649,
    oldPrice: 799,
    rating: 4.9,
    numReviews: 310,
    countInStock: 14,
    isFeatured: true,
    tags: ["espresso", "coffee", "luxury"],
    features: ["15-bar Italian pump", "Automated micro-foam steam wand", "Built-in conical burr grinder"],
    image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Damascus 8-inch Chef Knife",
    category: "Kitchen & Gourmet",
    brand: "KuroHagane",
    price: 139,
    oldPrice: 189,
    rating: 4.8,
    numReviews: 245,
    countInStock: 28,
    isFeatured: true,
    tags: ["knife", "japanese", "culinary"],
    features: ["67-layer VG-10 Damascus steel", "Ergonomic Pakkawood handle", "Razor-sharp 15-degree edge"],
    image: "https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Enameled Cast Iron Dutch Oven",
    category: "Kitchen & Gourmet",
    brand: "Fonte Cuisine",
    price: 129,
    oldPrice: 169,
    rating: 4.7,
    numReviews: 180,
    countInStock: 26,
    isFeatured: false,
    tags: ["cookware", "cast iron", "baking"],
    features: ["5.5-quart capacity", "Exceptional heat retention", "Oven safe up to 260C"],
    image: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Cold Brew Glass Drip Tower",
    category: "Kitchen & Gourmet",
    brand: "Crema & Bean",
    price: 89,
    oldPrice: 119,
    rating: 4.6,
    numReviews: 134,
    countInStock: 35,
    isFeatured: false,
    tags: ["cold brew", "coffee", "glass"],
    features: ["Borosilicate glass construction", "Adjustable drip control valve", "Fine stainless mesh filter"],
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Smart Digital Air Fryer Deluxe",
    category: "Kitchen & Gourmet",
    brand: "AeroCook",
    price: 149,
    oldPrice: 199,
    rating: 4.8,
    numReviews: 290,
    countInStock: 32,
    isFeatured: false,
    tags: ["air fryer", "healthy", "smart appliance"],
    features: ["6-quart nonstick basket", "12 one-touch cooking presets", "Syncs with recipe mobile app"],
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Precision Gooseneck Pour-Over Kettle",
    category: "Kitchen & Gourmet",
    brand: "Crema & Bean",
    price: 95,
    oldPrice: 125,
    rating: 4.8,
    numReviews: 212,
    countInStock: 30,
    isFeatured: true,
    tags: ["kettle", "pour over", "coffee"],
    features: ["Variable 1-degree temperature control", "Ergonomic balanced gooseneck spout", "Keep-warm mode for 60 minutes"],
    image: "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Artisan Walnut End-Grain Cutting Board",
    category: "Kitchen & Gourmet",
    brand: "Fonte Cuisine",
    price: 75,
    oldPrice: 99,
    rating: 4.7,
    numReviews: 168,
    countInStock: 36,
    isFeatured: false,
    tags: ["cutting board", "walnut", "woodcraft"],
    features: ["Sustainable American black walnut", "Self-healing end-grain construction", "Deep juice groove and recessed handles"],
    image: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Pro Ceramic Burr Electric Coffee Grinder",
    category: "Kitchen & Gourmet",
    brand: "Crema & Bean",
    price: 119,
    oldPrice: 159,
    rating: 4.9,
    numReviews: 240,
    countInStock: 25,
    isFeatured: false,
    tags: ["grinder", "coffee", "ceramic burr"],
    features: ["40 precise macro & micro grind settings", "Low-RPM motor reduces heat build-up", "Anti-static dosing cup included"],
    image: "https://images.unsplash.com/photo-1589396575653-c09c794ff6a6?auto=format&fit=crop&w=1200&q=80",
  },

  // 10. BOOKS & STATIONERY (NEW CATEGORY)
  {
    name: "Executive Leatherbound Journal",
    category: "Books & Stationery",
    brand: "Atelier Papyrus",
    price: 49,
    oldPrice: 65,
    rating: 4.8,
    numReviews: 188,
    countInStock: 55,
    isFeatured: false,
    tags: ["notebook", "journal", "stationery"],
    features: ["120gsm ink-proof bleed-free paper", "Supple full-grain leather cover", "Ribbon bookmark"],
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Handcrafted Brass Fountain Pen",
    category: "Books & Stationery",
    brand: "Veritas Pens",
    price: 85,
    oldPrice: 115,
    rating: 4.9,
    numReviews: 215,
    countInStock: 30,
    isFeatured: true,
    tags: ["fountain pen", "brass", "luxury"],
    features: ["German iridium fine nib", "Solid machined brass barrel", "Includes piston converter"],
    image: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Minimalist Oak Desk Organizer",
    category: "Books & Stationery",
    brand: "Atelier Papyrus",
    price: 64,
    oldPrice: 85,
    rating: 4.7,
    numReviews: 140,
    countInStock: 40,
    isFeatured: false,
    tags: ["desk organizer", "wood", "minimal"],
    features: ["Solid European white oak", "Dedicated phone & pen channels", "Felt-lined base"],
    image: "https://images.unsplash.com/photo-1507842229451-79b1be886a20?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Architectural Drafting Lamp",
    category: "Books & Stationery",
    brand: "Lumier Craft",
    price: 119,
    oldPrice: 155,
    rating: 4.6,
    numReviews: 122,
    countInStock: 25,
    isFeatured: false,
    tags: ["lamp", "study", "architect"],
    features: ["Counterbalanced spring arm", "CRI 95 true color lighting", "Stepless dimming control"],
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Masterclass Designer Planner",
    category: "Books & Stationery",
    brand: "Veritas Pens",
    price: 36,
    oldPrice: 48,
    rating: 4.7,
    numReviews: 160,
    countInStock: 65,
    isFeatured: false,
    tags: ["planner", "productivity", "calendar"],
    features: ["Undated 52-week system", "Habit trackers & goal frameworks", "Hardcover linen binding"],
    image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Heavyweight Archival Cotton Sketchbook",
    category: "Books & Stationery",
    brand: "Atelier Papyrus",
    price: 28,
    oldPrice: 38,
    rating: 4.8,
    numReviews: 172,
    countInStock: 60,
    isFeatured: false,
    tags: ["sketchbook", "art", "watercolor"],
    features: ["300gsm 100% cotton cold-press paper", "Lay-flat Smyth-sewn binding", "Acid-free archival durability"],
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Calligraphy Pen & Dip Ink Luxury Kit",
    category: "Books & Stationery",
    brand: "Veritas Pens",
    price: 52,
    oldPrice: 70,
    rating: 4.9,
    numReviews: 194,
    countInStock: 28,
    isFeatured: true,
    tags: ["calligraphy", "ink", "quill"],
    features: ["6 interchangeable stainless steel nibs", "Rich pigment archival sumi black ink", "Solid hand-turned wooden stylus"],
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80",
  },
  {
    name: "Anodized Aluminum Heavy Bookend Pair",
    category: "Books & Stationery",
    brand: "Lumier Craft",
    price: 44,
    oldPrice: 58,
    rating: 4.7,
    numReviews: 120,
    countInStock: 45,
    isFeatured: false,
    tags: ["bookends", "desk decor", "minimal"],
    features: ["Solid 4mm laser-cut aircraft aluminum", "Non-skid silicone base pads", "Sleek matte sandblasted finish"],
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80",
  },
];

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const sampleProducts = baseProducts.map((product, index) => {
  const isOnSale = product.oldPrice > product.price;
  const imageSet = [
    `${product.image}`,
    `${product.image}&sat=-8`,
    `${product.image}&hue=10`,
    `${product.image}&contrast=5`,
  ];

  return {
    name: product.name,
    slug: `${slugify(product.name)}-${index + 1}`,
    description: `${product.name} delivers premium design, reliable performance, and refined everyday experience for modern lifestyles.`,
    price: product.price,
    oldPrice: product.oldPrice,
    category: product.category,
    brand: product.brand,
    image: product.image,
    images: imageSet,
    rating: product.rating,
    numReviews: product.numReviews,
    countInStock: product.countInStock,
    isFeatured: product.isFeatured,
    isOnSale,
    tags: product.tags,
    features: product.features,
  };
});

async function seedProducts() {
  try {
    await connectDB();
    await Product.deleteMany({});
    await Product.insertMany(sampleProducts);
    console.log(`Seed complete: ${sampleProducts.length} premium products inserted across 10 categories`);
    process.exit(0);
  } catch (error) {
    console.error("Seed failed:", error.message);
    process.exit(1);
  }
}

seedProducts();
